// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnKeiWDD-SWw2791FwhbZWcbqnm1VEJYg',
    appId: '1:380296572966:web:abd223081c20650fa436e7',
    messagingSenderId: '380296572966',
    projectId: 'testproject-b9ac1',
    authDomain: 'testproject-b9ac1.firebaseapp.com',
    databaseURL: 'https://testproject-b9ac1-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-b9ac1.appspot.com',
    measurementId: 'G-TSGM9EDR52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNkAUcRPamWwm8bYWG5FCSjAeJYgYfnMY',
    appId: '1:380296572966:android:129cac1420c67f61a436e7',
    messagingSenderId: '380296572966',
    projectId: 'testproject-b9ac1',
    databaseURL: 'https://testproject-b9ac1-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-b9ac1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-PLo40kezJDbWgbZFmskKLfn61rb0JM4',
    appId: '1:380296572966:ios:d62f7fbc5e7adc47a436e7',
    messagingSenderId: '380296572966',
    projectId: 'testproject-b9ac1',
    databaseURL: 'https://testproject-b9ac1-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-b9ac1.appspot.com',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-PLo40kezJDbWgbZFmskKLfn61rb0JM4',
    appId: '1:380296572966:ios:d62f7fbc5e7adc47a436e7',
    messagingSenderId: '380296572966',
    projectId: 'testproject-b9ac1',
    databaseURL: 'https://testproject-b9ac1-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-b9ac1.appspot.com',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnKeiWDD-SWw2791FwhbZWcbqnm1VEJYg',
    appId: '1:380296572966:web:cf92b82a23e97b10a436e7',
    messagingSenderId: '380296572966',
    projectId: 'testproject-b9ac1',
    authDomain: 'testproject-b9ac1.firebaseapp.com',
    databaseURL: 'https://testproject-b9ac1-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-b9ac1.appspot.com',
    measurementId: 'G-Y5B366B4JQ',
  );

}